# -*- coding: utf-8 -*-
"""Income.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shqXVbJ1Imz32ZbJMS_2tFujyVYALzE9
"""

import streamlit as st

st.set_page_config(page_title="คำนวนเงินเดือน", layout="centered")

st.title("คำนวณรายได้แยกรายการ")

rate = st.number_input("ค่าแรงต่อวัน", value=100.0)
hourly = rate / 8

def calculate_wage(shift_type, rate, hourly):
    """คำนวณค่าแรงตามประเภทกะ"""
    if shift_type in ['A', 'C']:
        return rate
    elif shift_type in ['D', 'E']:
        return (rate) + (hourly * 1.5 * 2.5)
    elif shift_type in ['OTD', 'OTE']:
        return (rate * 2) + (hourly * 2.5 * 3)
    else:
        return 0

def calculate_meal(shift_type):
    """คำนวณค่าอาหารตามประเภทกะ"""
    if shift_type in ['A', 'C']:
        return 20
    elif shift_type in ['D', 'E']:
        return 35
    elif shift_type in ['OTD', 'OTE']:
        return 50
    else:
        return 0

def calculate_shift(shift_type):
    """คำนวณค่ากะตามประเภทกะ"""
    if shift_type in ['A', 'D', 'OTD']:
        return 10
    elif shift_type in ['C', 'E', 'OTE']:
        return 60
    else:
        return 0

# Input วันแต่ละกะ
st.subheader("จำนวนวันแต่ละกะ")
col1, col2, col3 = st.columns(3)

A = col1.number_input("A (เช้า)", 0, step=1, key='A_count')
D = col2.number_input("D (A+OT)", 0, step=1, key='D_count')
C = col3.number_input("C (ดึก)", 0, step=1, key='C_count')
E = col1.number_input("E (C+OT)", 0, step=1, key='E_count')
OTD = col2.number_input("OTD (วันหยุด)", 0, step=1, key='OTD_count')
OTE = col3.number_input("OTE (หยุด+ดึก)", 0, step=1, key='OTE_count')

# ข้อมูลแต่ละกะ
shifts = {
    'A': {'label': 'กะ A', 'count': A},
    'D': {'label': 'กะ D', 'count': D},
    'C': {'label': 'กะ C', 'count': C},
    'E': {'label': 'กะ E', 'count': E},
    'OTD': {'label': 'OTD', 'count': OTD},
    'OTE': {'label': 'OTE', 'count': OTE}
}

# คำนวณ
wage_total = meal_total = shift_total = total = 0

st.subheader("ผลลัพธ์")

for key, s in shifts.items():
    if s['count'] > 0:
        wage = calculate_wage(key, rate, hourly) * s['count']
        meal = calculate_meal(key) * s['count']
        shift = calculate_shift(key) * s['count']
        total_part = wage + meal + shift

        st.markdown(f"**{s['label']} × {s['count']} วัน**")
        st.markdown(f"- ค่าแรงรวม: {wage:,.2f} บาท")
        st.markdown(f"- ค่าข้าวรวม: {meal:,.2f} บาท")
        st.markdown(f"- ค่ากะรวม: {shift:,.2f} บาท")
        st.markdown(f"**ยอดรวม: {total_part:,.2f} บาท**")
        st.markdown("---")

        wage_total += wage
        meal_total += meal
        shift_total += shift
        total += total_part

# สรุปรวม
st.subheader("รวมทั้งหมด")
st.markdown(f"**ค่าแรงรวม:** {wage_total:,.2f} บาท")
st.markdown(f"**ค่าข้าวรวม:** {meal_total:,.2f} บาท")
st.markdown(f"**ค่ากะรวม:** {shift_total:,.2f} บาท")
st.markdown(f"**รวมสุทธิ:** {total:,.2f} บาท")
